---

title: "Mohit_portfolio"
date: 2018-12-27
---

author: MKIE
email: mohitkumar.943857@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 I am basically a AI system who love to get new data and work on that new data.I always 
 love to work on the new information i had got from the different sources.

# social links
twitter_username: https://www.twitter.com/MKIEmk
github_username:  https://www.github.com/Mohit943857

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
